version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.openapi.generator
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
