openapi: 3.0.0
info:
  title: Spring Boot Todo
  description: Todo application by Spring Boot
  version: 0.1.0
servers:
  - url: https://example.com/api/v0
    description: production API
  - url: http://{host}:{port}/api/v0
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '10080'
paths:
  /:
    get:
      summary: List all tasks
      operationId: listTasks
      responses:
        '200':
          description: array of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
  /tasks/new:
    post:
      summary: add a new task
      operationId: addTask
      requestBody:
        description: task to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/{taskId}:
    put:
      summary: edit a task
      operationId: editTask
      parameters: 
        - name: taskId
          in: path
          required: true
          description: id of task
          schema:
            type: string
      responses:
        '201':
          description: edited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: archive done tasks
      operationId: archiveTasks
      parameters: 
        - name: taskId
          in: path
          required: true
          description: id of task
          schema:
            type: string
      responses:
        '200':
          description: archived task
        default:
          description: unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/{taskId}/done:
    put:
      summary: make the task done
      operationId: doneTask
      parameters: 
        - name: taskId
          in: path
          required: true
          description: id of task
          schema:
            type: string
      responses:
        '200':
          description: done
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/{taskId}/undone:
    put:
      summary: make the task undone
      operationId: undoneTask
      parameters: 
        - name: taskId
          in: path
          required: true
          description: id of task
          schema:
            type: string
      responses:
        '200':
          description: done
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Task:
      description: one task object
      type: object
      required:
        - id
        - content
        - urgent
        - important
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        urgent:
          type: integer
          format: int64
        important:
          type: integer
          format: int64
        done:
          type: boolean
    Tasks:
      type: array
      items:
        $ref: '#/components/schemas/Task'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string