CREATE TABLE IF NOT EXISTS task
(
 id                 SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
 name               VARCHAR(100) NOT NULL,
 urgency            TINYINT UNSIGNED NOT NULL,
 importance         TINYINT UNSIGNED NOT NULL,
 created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 is_done            TINYINT(1) NOT NULL,

 INDEX USING BTREE (is_disabled)
) ENGINE = 'InnoDB';